// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/command.proto

// Protobuf Java Version: 3.25.5
package com.nailong.xt.proto.server;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CmdReqContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nailong.xt.proto.server.CmdReqContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    int getCmdId();

    /**
     * <code>bytes proto_data = 2;</code>
     * @return The protoData.
     */
    com.google.protobuf.ByteString getProtoData();

    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int64 account_uid = 102;</code>
     * @return The accountUid.
     */
    long getAccountUid();

    /**
     * <code>int32 player_uid = 103;</code>
     * @return The playerUid.
     */
    int getPlayerUid();

    /**
     * <code>uint64 timestamp = 201;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * 请求与响应容器（维持你的核心结构）
   * </pre>
   *
   * Protobuf type {@code com.nailong.xt.proto.server.CmdReqContext}
   */
  public static final class CmdReqContext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nailong.xt.proto.server.CmdReqContext)
      CmdReqContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmdReqContext.newBuilder() to construct.
    private CmdReqContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmdReqContext() {
      protoData_ = com.google.protobuf.ByteString.EMPTY;
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmdReqContext();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdReqContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nailong.xt.proto.server.Command.CmdReqContext.class, com.nailong.xt.proto.server.Command.CmdReqContext.Builder.class);
    }

    public static final int CMD_ID_FIELD_NUMBER = 1;
    private int cmdId_ = 0;
    /**
     * <code>uint32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }

    public static final int PROTO_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes proto_data = 2;</code>
     * @return The protoData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtoData() {
      return protoData_;
    }

    public static final int TOKEN_FIELD_NUMBER = 101;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_UID_FIELD_NUMBER = 102;
    private long accountUid_ = 0L;
    /**
     * <code>int64 account_uid = 102;</code>
     * @return The accountUid.
     */
    @java.lang.Override
    public long getAccountUid() {
      return accountUid_;
    }

    public static final int PLAYER_UID_FIELD_NUMBER = 103;
    private int playerUid_ = 0;
    /**
     * <code>int32 player_uid = 103;</code>
     * @return The playerUid.
     */
    @java.lang.Override
    public int getPlayerUid() {
      return playerUid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 201;
    private long timestamp_ = 0L;
    /**
     * <code>uint64 timestamp = 201;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdId_ != 0) {
        output.writeUInt32(1, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        output.writeBytes(2, protoData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 101, token_);
      }
      if (accountUid_ != 0L) {
        output.writeInt64(102, accountUid_);
      }
      if (playerUid_ != 0) {
        output.writeInt32(103, playerUid_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(201, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, protoData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, token_);
      }
      if (accountUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(102, accountUid_);
      }
      if (playerUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(103, playerUid_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(201, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nailong.xt.proto.server.Command.CmdReqContext)) {
        return super.equals(obj);
      }
      com.nailong.xt.proto.server.Command.CmdReqContext other = (com.nailong.xt.proto.server.Command.CmdReqContext) obj;

      if (getCmdId()
          != other.getCmdId()) return false;
      if (!getProtoData()
          .equals(other.getProtoData())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getAccountUid()
          != other.getAccountUid()) return false;
      if (getPlayerUid()
          != other.getPlayerUid()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      hash = (37 * hash) + PROTO_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getProtoData().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ACCOUNT_UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAccountUid());
      hash = (37 * hash) + PLAYER_UID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerUid();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nailong.xt.proto.server.Command.CmdReqContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nailong.xt.proto.server.Command.CmdReqContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Command.CmdReqContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nailong.xt.proto.server.Command.CmdReqContext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求与响应容器（维持你的核心结构）
     * </pre>
     *
     * Protobuf type {@code com.nailong.xt.proto.server.CmdReqContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nailong.xt.proto.server.CmdReqContext)
        com.nailong.xt.proto.server.Command.CmdReqContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdReqContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nailong.xt.proto.server.Command.CmdReqContext.class, com.nailong.xt.proto.server.Command.CmdReqContext.Builder.class);
      }

      // Construct using com.nailong.xt.proto.server.Command.CmdReqContext.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdId_ = 0;
        protoData_ = com.google.protobuf.ByteString.EMPTY;
        token_ = "";
        accountUid_ = 0L;
        playerUid_ = 0;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdReqContext getDefaultInstanceForType() {
        return com.nailong.xt.proto.server.Command.CmdReqContext.getDefaultInstance();
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdReqContext build() {
        com.nailong.xt.proto.server.Command.CmdReqContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdReqContext buildPartial() {
        com.nailong.xt.proto.server.Command.CmdReqContext result = new com.nailong.xt.proto.server.Command.CmdReqContext(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nailong.xt.proto.server.Command.CmdReqContext result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdId_ = cmdId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.protoData_ = protoData_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.accountUid_ = accountUid_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.playerUid_ = playerUid_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nailong.xt.proto.server.Command.CmdReqContext) {
          return mergeFrom((com.nailong.xt.proto.server.Command.CmdReqContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nailong.xt.proto.server.Command.CmdReqContext other) {
        if (other == com.nailong.xt.proto.server.Command.CmdReqContext.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.getProtoData() != com.google.protobuf.ByteString.EMPTY) {
          setProtoData(other.getProtoData());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getAccountUid() != 0L) {
          setAccountUid(other.getAccountUid());
        }
        if (other.getPlayerUid() != 0) {
          setPlayerUid(other.getPlayerUid());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cmdId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                protoData_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 810: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 810
              case 816: {
                accountUid_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 816
              case 824: {
                playerUid_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 824
              case 1608: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 1608
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdId_ ;
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @return The cmdId.
       */
      @java.lang.Override
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @param value The cmdId to set.
       * @return This builder for chaining.
       */
      public Builder setCmdId(int value) {

        cmdId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes proto_data = 2;</code>
       * @return The protoData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getProtoData() {
        return protoData_;
      }
      /**
       * <code>bytes proto_data = 2;</code>
       * @param value The protoData to set.
       * @return This builder for chaining.
       */
      public Builder setProtoData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        protoData_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes proto_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtoData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        protoData_ = getDefaultInstance().getProtoData();
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long accountUid_ ;
      /**
       * <code>int64 account_uid = 102;</code>
       * @return The accountUid.
       */
      @java.lang.Override
      public long getAccountUid() {
        return accountUid_;
      }
      /**
       * <code>int64 account_uid = 102;</code>
       * @param value The accountUid to set.
       * @return This builder for chaining.
       */
      public Builder setAccountUid(long value) {

        accountUid_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 account_uid = 102;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accountUid_ = 0L;
        onChanged();
        return this;
      }

      private int playerUid_ ;
      /**
       * <code>int32 player_uid = 103;</code>
       * @return The playerUid.
       */
      @java.lang.Override
      public int getPlayerUid() {
        return playerUid_;
      }
      /**
       * <code>int32 player_uid = 103;</code>
       * @param value The playerUid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerUid(int value) {

        playerUid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_uid = 103;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playerUid_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 201;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 201;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 201;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nailong.xt.proto.server.CmdReqContext)
    }

    // @@protoc_insertion_point(class_scope:com.nailong.xt.proto.server.CmdReqContext)
    private static final com.nailong.xt.proto.server.Command.CmdReqContext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nailong.xt.proto.server.Command.CmdReqContext();
    }

    public static com.nailong.xt.proto.server.Command.CmdReqContext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdReqContext>
        PARSER = new com.google.protobuf.AbstractParser<CmdReqContext>() {
      @java.lang.Override
      public CmdReqContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CmdReqContext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdReqContext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nailong.xt.proto.server.Command.CmdReqContext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CmdRspContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nailong.xt.proto.server.CmdRspContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 响应对应的命令ID
     * </pre>
     *
     * <code>uint32 cmd_id = 1001;</code>
     * @return The cmdId.
     */
    int getCmdId();

    /**
     * <pre>
     * 对应的请求命令ID，用于关联
     * </pre>
     *
     * <code>uint32 req_cmd_id = 1003;</code>
     * @return The reqCmdId.
     */
    int getReqCmdId();

    /**
     * <code>bytes proto_data = 1002;</code>
     * @return The protoData.
     */
    com.google.protobuf.ByteString getProtoData();

    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 1005;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 1005;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>uint32 player_uid = 1007;</code>
     * @return The playerUid.
     */
    int getPlayerUid();

    /**
     * <code>uint64 timestamp = 1004;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * todo 以后用专属类型
     * </pre>
     *
     * <code>bool is_failed = 1008;</code>
     * @return The isFailed.
     */
    boolean getIsFailed();
  }
  /**
   * Protobuf type {@code com.nailong.xt.proto.server.CmdRspContext}
   */
  public static final class CmdRspContext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nailong.xt.proto.server.CmdRspContext)
      CmdRspContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmdRspContext.newBuilder() to construct.
    private CmdRspContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmdRspContext() {
      protoData_ = com.google.protobuf.ByteString.EMPTY;
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmdRspContext();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdRspContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nailong.xt.proto.server.Command.CmdRspContext.class, com.nailong.xt.proto.server.Command.CmdRspContext.Builder.class);
    }

    public static final int CMD_ID_FIELD_NUMBER = 1001;
    private int cmdId_ = 0;
    /**
     * <pre>
     * 响应对应的命令ID
     * </pre>
     *
     * <code>uint32 cmd_id = 1001;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }

    public static final int REQ_CMD_ID_FIELD_NUMBER = 1003;
    private int reqCmdId_ = 0;
    /**
     * <pre>
     * 对应的请求命令ID，用于关联
     * </pre>
     *
     * <code>uint32 req_cmd_id = 1003;</code>
     * @return The reqCmdId.
     */
    @java.lang.Override
    public int getReqCmdId() {
      return reqCmdId_;
    }

    public static final int PROTO_DATA_FIELD_NUMBER = 1002;
    private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes proto_data = 1002;</code>
     * @return The protoData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtoData() {
      return protoData_;
    }

    public static final int TOKEN_FIELD_NUMBER = 1005;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 1005;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 1005;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER_UID_FIELD_NUMBER = 1007;
    private int playerUid_ = 0;
    /**
     * <code>uint32 player_uid = 1007;</code>
     * @return The playerUid.
     */
    @java.lang.Override
    public int getPlayerUid() {
      return playerUid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1004;
    private long timestamp_ = 0L;
    /**
     * <code>uint64 timestamp = 1004;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IS_FAILED_FIELD_NUMBER = 1008;
    private boolean isFailed_ = false;
    /**
     * <pre>
     * todo 以后用专属类型
     * </pre>
     *
     * <code>bool is_failed = 1008;</code>
     * @return The isFailed.
     */
    @java.lang.Override
    public boolean getIsFailed() {
      return isFailed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdId_ != 0) {
        output.writeUInt32(1001, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        output.writeBytes(1002, protoData_);
      }
      if (reqCmdId_ != 0) {
        output.writeUInt32(1003, reqCmdId_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(1004, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1005, token_);
      }
      if (playerUid_ != 0) {
        output.writeUInt32(1007, playerUid_);
      }
      if (isFailed_ != false) {
        output.writeBool(1008, isFailed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1001, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1002, protoData_);
      }
      if (reqCmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1003, reqCmdId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1004, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1005, token_);
      }
      if (playerUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1007, playerUid_);
      }
      if (isFailed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1008, isFailed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nailong.xt.proto.server.Command.CmdRspContext)) {
        return super.equals(obj);
      }
      com.nailong.xt.proto.server.Command.CmdRspContext other = (com.nailong.xt.proto.server.Command.CmdRspContext) obj;

      if (getCmdId()
          != other.getCmdId()) return false;
      if (getReqCmdId()
          != other.getReqCmdId()) return false;
      if (!getProtoData()
          .equals(other.getProtoData())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getPlayerUid()
          != other.getPlayerUid()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getIsFailed()
          != other.getIsFailed()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      hash = (37 * hash) + REQ_CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReqCmdId();
      hash = (37 * hash) + PROTO_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getProtoData().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + PLAYER_UID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerUid();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + IS_FAILED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFailed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nailong.xt.proto.server.Command.CmdRspContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nailong.xt.proto.server.Command.CmdRspContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Command.CmdRspContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nailong.xt.proto.server.Command.CmdRspContext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nailong.xt.proto.server.CmdRspContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nailong.xt.proto.server.CmdRspContext)
        com.nailong.xt.proto.server.Command.CmdRspContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdRspContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nailong.xt.proto.server.Command.CmdRspContext.class, com.nailong.xt.proto.server.Command.CmdRspContext.Builder.class);
      }

      // Construct using com.nailong.xt.proto.server.Command.CmdRspContext.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdId_ = 0;
        reqCmdId_ = 0;
        protoData_ = com.google.protobuf.ByteString.EMPTY;
        token_ = "";
        playerUid_ = 0;
        timestamp_ = 0L;
        isFailed_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nailong.xt.proto.server.Command.internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdRspContext getDefaultInstanceForType() {
        return com.nailong.xt.proto.server.Command.CmdRspContext.getDefaultInstance();
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdRspContext build() {
        com.nailong.xt.proto.server.Command.CmdRspContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Command.CmdRspContext buildPartial() {
        com.nailong.xt.proto.server.Command.CmdRspContext result = new com.nailong.xt.proto.server.Command.CmdRspContext(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nailong.xt.proto.server.Command.CmdRspContext result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdId_ = cmdId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reqCmdId_ = reqCmdId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.protoData_ = protoData_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.playerUid_ = playerUid_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isFailed_ = isFailed_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nailong.xt.proto.server.Command.CmdRspContext) {
          return mergeFrom((com.nailong.xt.proto.server.Command.CmdRspContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nailong.xt.proto.server.Command.CmdRspContext other) {
        if (other == com.nailong.xt.proto.server.Command.CmdRspContext.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.getReqCmdId() != 0) {
          setReqCmdId(other.getReqCmdId());
        }
        if (other.getProtoData() != com.google.protobuf.ByteString.EMPTY) {
          setProtoData(other.getProtoData());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getPlayerUid() != 0) {
          setPlayerUid(other.getPlayerUid());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getIsFailed() != false) {
          setIsFailed(other.getIsFailed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8008: {
                cmdId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8008
              case 8018: {
                protoData_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 8018
              case 8024: {
                reqCmdId_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 8024
              case 8032: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 8032
              case 8042: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 8042
              case 8056: {
                playerUid_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 8056
              case 8064: {
                isFailed_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 8064
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdId_ ;
      /**
       * <pre>
       * 响应对应的命令ID
       * </pre>
       *
       * <code>uint32 cmd_id = 1001;</code>
       * @return The cmdId.
       */
      @java.lang.Override
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <pre>
       * 响应对应的命令ID
       * </pre>
       *
       * <code>uint32 cmd_id = 1001;</code>
       * @param value The cmdId to set.
       * @return This builder for chaining.
       */
      public Builder setCmdId(int value) {

        cmdId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应对应的命令ID
       * </pre>
       *
       * <code>uint32 cmd_id = 1001;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private int reqCmdId_ ;
      /**
       * <pre>
       * 对应的请求命令ID，用于关联
       * </pre>
       *
       * <code>uint32 req_cmd_id = 1003;</code>
       * @return The reqCmdId.
       */
      @java.lang.Override
      public int getReqCmdId() {
        return reqCmdId_;
      }
      /**
       * <pre>
       * 对应的请求命令ID，用于关联
       * </pre>
       *
       * <code>uint32 req_cmd_id = 1003;</code>
       * @param value The reqCmdId to set.
       * @return This builder for chaining.
       */
      public Builder setReqCmdId(int value) {

        reqCmdId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应的请求命令ID，用于关联
       * </pre>
       *
       * <code>uint32 req_cmd_id = 1003;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqCmdId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqCmdId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes proto_data = 1002;</code>
       * @return The protoData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getProtoData() {
        return protoData_;
      }
      /**
       * <code>bytes proto_data = 1002;</code>
       * @param value The protoData to set.
       * @return This builder for chaining.
       */
      public Builder setProtoData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        protoData_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes proto_data = 1002;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtoData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        protoData_ = getDefaultInstance().getProtoData();
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 1005;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 1005;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 1005;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 1005;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 1005;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int playerUid_ ;
      /**
       * <code>uint32 player_uid = 1007;</code>
       * @return The playerUid.
       */
      @java.lang.Override
      public int getPlayerUid() {
        return playerUid_;
      }
      /**
       * <code>uint32 player_uid = 1007;</code>
       * @param value The playerUid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerUid(int value) {

        playerUid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 player_uid = 1007;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playerUid_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 1004;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 1004;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 1004;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean isFailed_ ;
      /**
       * <pre>
       * todo 以后用专属类型
       * </pre>
       *
       * <code>bool is_failed = 1008;</code>
       * @return The isFailed.
       */
      @java.lang.Override
      public boolean getIsFailed() {
        return isFailed_;
      }
      /**
       * <pre>
       * todo 以后用专属类型
       * </pre>
       *
       * <code>bool is_failed = 1008;</code>
       * @param value The isFailed to set.
       * @return This builder for chaining.
       */
      public Builder setIsFailed(boolean value) {

        isFailed_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * todo 以后用专属类型
       * </pre>
       *
       * <code>bool is_failed = 1008;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFailed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isFailed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nailong.xt.proto.server.CmdRspContext)
    }

    // @@protoc_insertion_point(class_scope:com.nailong.xt.proto.server.CmdRspContext)
    private static final com.nailong.xt.proto.server.Command.CmdRspContext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nailong.xt.proto.server.Command.CmdRspContext();
    }

    public static com.nailong.xt.proto.server.Command.CmdRspContext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdRspContext>
        PARSER = new com.google.protobuf.AbstractParser<CmdRspContext>() {
      @java.lang.Override
      public CmdRspContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CmdRspContext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdRspContext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nailong.xt.proto.server.Command.CmdRspContext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nailong_xt_proto_server_CmdReqContext_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nailong_xt_proto_server_CmdRspContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024server/command.proto\022\033com.nailong.xt.p" +
      "roto.server\"\177\n\rCmdReqContext\022\016\n\006cmd_id\030\001" +
      " \001(\r\022\022\n\nproto_data\030\002 \001(\014\022\r\n\005token\030e \001(\t\022" +
      "\023\n\013account_uid\030f \001(\003\022\022\n\nplayer_uid\030g \001(\005" +
      "\022\022\n\ttimestamp\030\311\001 \001(\004\"\227\001\n\rCmdRspContext\022\017" +
      "\n\006cmd_id\030\351\007 \001(\r\022\023\n\nreq_cmd_id\030\353\007 \001(\r\022\023\n\n" +
      "proto_data\030\352\007 \001(\014\022\016\n\005token\030\355\007 \001(\t\022\023\n\npla" +
      "yer_uid\030\357\007 \001(\r\022\022\n\ttimestamp\030\354\007 \001(\004\022\022\n\tis" +
      "_failed\030\360\007 \001(\0102\205\001\n\024PlayerCommandService\022" +
      "m\n\023HandlePlayerRequest\022*.com.nailong.xt." +
      "proto.server.CmdReqContext\032*.com.nailong" +
      ".xt.proto.server.CmdRspContextb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nailong_xt_proto_server_CmdReqContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nailong_xt_proto_server_CmdReqContext_descriptor,
        new java.lang.String[] { "CmdId", "ProtoData", "Token", "AccountUid", "PlayerUid", "Timestamp", });
    internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nailong_xt_proto_server_CmdRspContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nailong_xt_proto_server_CmdRspContext_descriptor,
        new java.lang.String[] { "CmdId", "ReqCmdId", "ProtoData", "Token", "PlayerUid", "Timestamp", "IsFailed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
