// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/push.proto

// Protobuf Java Version: 3.25.5
package com.nailong.xt.proto.server;

public final class Push {
  private Push() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushPacketNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nailong.xt.proto.server.PushPacketNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    int getCmdId();

    /**
     * <code>bytes proto_data = 2;</code>
     * @return The protoData.
     */
    com.google.protobuf.ByteString getProtoData();

    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @return A list containing the targetPlayerUids.
     */
    java.util.List<java.lang.Integer> getTargetPlayerUidsList();
    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @return The count of targetPlayerUids.
     */
    int getTargetPlayerUidsCount();
    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @param index The index of the element to return.
     * @return The targetPlayerUids at the given index.
     */
    int getTargetPlayerUids(int index);

    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int64 account_uid = 102;</code>
     * @return The accountUid.
     */
    long getAccountUid();

    /**
     * <code>uint64 timestamp = 201;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * 推送消息容器
   * </pre>
   *
   * Protobuf type {@code com.nailong.xt.proto.server.PushPacketNotify}
   */
  public static final class PushPacketNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nailong.xt.proto.server.PushPacketNotify)
      PushPacketNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushPacketNotify.newBuilder() to construct.
    private PushPacketNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushPacketNotify() {
      protoData_ = com.google.protobuf.ByteString.EMPTY;
      targetPlayerUids_ = emptyIntList();
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PushPacketNotify();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_PushPacketNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nailong.xt.proto.server.Push.PushPacketNotify.class, com.nailong.xt.proto.server.Push.PushPacketNotify.Builder.class);
    }

    public static final int CMD_ID_FIELD_NUMBER = 1;
    private int cmdId_ = 0;
    /**
     * <code>uint32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }

    public static final int PROTO_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes proto_data = 2;</code>
     * @return The protoData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtoData() {
      return protoData_;
    }

    public static final int TARGET_PLAYER_UIDS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList targetPlayerUids_ =
        emptyIntList();
    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @return A list containing the targetPlayerUids.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getTargetPlayerUidsList() {
      return targetPlayerUids_;
    }
    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @return The count of targetPlayerUids.
     */
    public int getTargetPlayerUidsCount() {
      return targetPlayerUids_.size();
    }
    /**
     * <pre>
     * 可以指定接收者列表，由Gate负责分发
     * </pre>
     *
     * <code>repeated uint32 target_player_uids = 3;</code>
     * @param index The index of the element to return.
     * @return The targetPlayerUids at the given index.
     */
    public int getTargetPlayerUids(int index) {
      return targetPlayerUids_.getInt(index);
    }
    private int targetPlayerUidsMemoizedSerializedSize = -1;

    public static final int TOKEN_FIELD_NUMBER = 101;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 元数据
     * </pre>
     *
     * <code>string token = 101;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_UID_FIELD_NUMBER = 102;
    private long accountUid_ = 0L;
    /**
     * <code>int64 account_uid = 102;</code>
     * @return The accountUid.
     */
    @java.lang.Override
    public long getAccountUid() {
      return accountUid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 201;
    private long timestamp_ = 0L;
    /**
     * <code>uint64 timestamp = 201;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (cmdId_ != 0) {
        output.writeUInt32(1, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        output.writeBytes(2, protoData_);
      }
      if (getTargetPlayerUidsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(targetPlayerUidsMemoizedSerializedSize);
      }
      for (int i = 0; i < targetPlayerUids_.size(); i++) {
        output.writeUInt32NoTag(targetPlayerUids_.getInt(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 101, token_);
      }
      if (accountUid_ != 0L) {
        output.writeInt64(102, accountUid_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(201, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cmdId_);
      }
      if (!protoData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, protoData_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < targetPlayerUids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(targetPlayerUids_.getInt(i));
        }
        size += dataSize;
        if (!getTargetPlayerUidsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        targetPlayerUidsMemoizedSerializedSize = dataSize;
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, token_);
      }
      if (accountUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(102, accountUid_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(201, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nailong.xt.proto.server.Push.PushPacketNotify)) {
        return super.equals(obj);
      }
      com.nailong.xt.proto.server.Push.PushPacketNotify other = (com.nailong.xt.proto.server.Push.PushPacketNotify) obj;

      if (getCmdId()
          != other.getCmdId()) return false;
      if (!getProtoData()
          .equals(other.getProtoData())) return false;
      if (!getTargetPlayerUidsList()
          .equals(other.getTargetPlayerUidsList())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getAccountUid()
          != other.getAccountUid()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      hash = (37 * hash) + PROTO_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getProtoData().hashCode();
      if (getTargetPlayerUidsCount() > 0) {
        hash = (37 * hash) + TARGET_PLAYER_UIDS_FIELD_NUMBER;
        hash = (53 * hash) + getTargetPlayerUidsList().hashCode();
      }
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ACCOUNT_UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAccountUid());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Push.PushPacketNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nailong.xt.proto.server.Push.PushPacketNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 推送消息容器
     * </pre>
     *
     * Protobuf type {@code com.nailong.xt.proto.server.PushPacketNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nailong.xt.proto.server.PushPacketNotify)
        com.nailong.xt.proto.server.Push.PushPacketNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_PushPacketNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nailong.xt.proto.server.Push.PushPacketNotify.class, com.nailong.xt.proto.server.Push.PushPacketNotify.Builder.class);
      }

      // Construct using com.nailong.xt.proto.server.Push.PushPacketNotify.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdId_ = 0;
        protoData_ = com.google.protobuf.ByteString.EMPTY;
        targetPlayerUids_ = emptyIntList();
        token_ = "";
        accountUid_ = 0L;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.PushPacketNotify getDefaultInstanceForType() {
        return com.nailong.xt.proto.server.Push.PushPacketNotify.getDefaultInstance();
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.PushPacketNotify build() {
        com.nailong.xt.proto.server.Push.PushPacketNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.PushPacketNotify buildPartial() {
        com.nailong.xt.proto.server.Push.PushPacketNotify result = new com.nailong.xt.proto.server.Push.PushPacketNotify(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nailong.xt.proto.server.Push.PushPacketNotify result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdId_ = cmdId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.protoData_ = protoData_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          targetPlayerUids_.makeImmutable();
          result.targetPlayerUids_ = targetPlayerUids_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.accountUid_ = accountUid_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nailong.xt.proto.server.Push.PushPacketNotify) {
          return mergeFrom((com.nailong.xt.proto.server.Push.PushPacketNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nailong.xt.proto.server.Push.PushPacketNotify other) {
        if (other == com.nailong.xt.proto.server.Push.PushPacketNotify.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.getProtoData() != com.google.protobuf.ByteString.EMPTY) {
          setProtoData(other.getProtoData());
        }
        if (!other.targetPlayerUids_.isEmpty()) {
          if (targetPlayerUids_.isEmpty()) {
            targetPlayerUids_ = other.targetPlayerUids_;
            targetPlayerUids_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureTargetPlayerUidsIsMutable();
            targetPlayerUids_.addAll(other.targetPlayerUids_);
          }
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getAccountUid() != 0L) {
          setAccountUid(other.getAccountUid());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cmdId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                protoData_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int v = input.readUInt32();
                ensureTargetPlayerUidsIsMutable();
                targetPlayerUids_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureTargetPlayerUidsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  targetPlayerUids_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 810: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 810
              case 816: {
                accountUid_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 816
              case 1608: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 1608
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdId_ ;
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @return The cmdId.
       */
      @java.lang.Override
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @param value The cmdId to set.
       * @return This builder for chaining.
       */
      public Builder setCmdId(int value) {

        cmdId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cmd_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes proto_data = 2;</code>
       * @return The protoData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getProtoData() {
        return protoData_;
      }
      /**
       * <code>bytes proto_data = 2;</code>
       * @param value The protoData to set.
       * @return This builder for chaining.
       */
      public Builder setProtoData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        protoData_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes proto_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtoData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        protoData_ = getDefaultInstance().getProtoData();
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList targetPlayerUids_ = emptyIntList();
      private void ensureTargetPlayerUidsIsMutable() {
        if (!targetPlayerUids_.isModifiable()) {
          targetPlayerUids_ = makeMutableCopy(targetPlayerUids_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @return A list containing the targetPlayerUids.
       */
      public java.util.List<java.lang.Integer>
          getTargetPlayerUidsList() {
        targetPlayerUids_.makeImmutable();
        return targetPlayerUids_;
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @return The count of targetPlayerUids.
       */
      public int getTargetPlayerUidsCount() {
        return targetPlayerUids_.size();
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @param index The index of the element to return.
       * @return The targetPlayerUids at the given index.
       */
      public int getTargetPlayerUids(int index) {
        return targetPlayerUids_.getInt(index);
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @param index The index to set the value at.
       * @param value The targetPlayerUids to set.
       * @return This builder for chaining.
       */
      public Builder setTargetPlayerUids(
          int index, int value) {

        ensureTargetPlayerUidsIsMutable();
        targetPlayerUids_.setInt(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @param value The targetPlayerUids to add.
       * @return This builder for chaining.
       */
      public Builder addTargetPlayerUids(int value) {

        ensureTargetPlayerUidsIsMutable();
        targetPlayerUids_.addInt(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @param values The targetPlayerUids to add.
       * @return This builder for chaining.
       */
      public Builder addAllTargetPlayerUids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTargetPlayerUidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targetPlayerUids_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以指定接收者列表，由Gate负责分发
       * </pre>
       *
       * <code>repeated uint32 target_player_uids = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetPlayerUids() {
        targetPlayerUids_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 元数据
       * </pre>
       *
       * <code>string token = 101;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private long accountUid_ ;
      /**
       * <code>int64 account_uid = 102;</code>
       * @return The accountUid.
       */
      @java.lang.Override
      public long getAccountUid() {
        return accountUid_;
      }
      /**
       * <code>int64 account_uid = 102;</code>
       * @param value The accountUid to set.
       * @return This builder for chaining.
       */
      public Builder setAccountUid(long value) {

        accountUid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 account_uid = 102;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accountUid_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 201;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 201;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 201;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nailong.xt.proto.server.PushPacketNotify)
    }

    // @@protoc_insertion_point(class_scope:com.nailong.xt.proto.server.PushPacketNotify)
    private static final com.nailong.xt.proto.server.Push.PushPacketNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nailong.xt.proto.server.Push.PushPacketNotify();
    }

    public static com.nailong.xt.proto.server.Push.PushPacketNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushPacketNotify>
        PARSER = new com.google.protobuf.AbstractParser<PushPacketNotify>() {
      @java.lang.Override
      public PushPacketNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PushPacketNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushPacketNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nailong.xt.proto.server.Push.PushPacketNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NoneMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nailong.xt.proto.server.NoneMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 为什么 dubbo 不支持 google.protobuf.Empty
   * </pre>
   *
   * Protobuf type {@code com.nailong.xt.proto.server.NoneMessage}
   */
  public static final class NoneMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nailong.xt.proto.server.NoneMessage)
      NoneMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NoneMessage.newBuilder() to construct.
    private NoneMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoneMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NoneMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_NoneMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nailong.xt.proto.server.Push.NoneMessage.class, com.nailong.xt.proto.server.Push.NoneMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nailong.xt.proto.server.Push.NoneMessage)) {
        return super.equals(obj);
      }
      com.nailong.xt.proto.server.Push.NoneMessage other = (com.nailong.xt.proto.server.Push.NoneMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nailong.xt.proto.server.Push.NoneMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nailong.xt.proto.server.Push.NoneMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nailong.xt.proto.server.Push.NoneMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nailong.xt.proto.server.Push.NoneMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 为什么 dubbo 不支持 google.protobuf.Empty
     * </pre>
     *
     * Protobuf type {@code com.nailong.xt.proto.server.NoneMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nailong.xt.proto.server.NoneMessage)
        com.nailong.xt.proto.server.Push.NoneMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_NoneMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nailong.xt.proto.server.Push.NoneMessage.class, com.nailong.xt.proto.server.Push.NoneMessage.Builder.class);
      }

      // Construct using com.nailong.xt.proto.server.Push.NoneMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nailong.xt.proto.server.Push.internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.NoneMessage getDefaultInstanceForType() {
        return com.nailong.xt.proto.server.Push.NoneMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.NoneMessage build() {
        com.nailong.xt.proto.server.Push.NoneMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nailong.xt.proto.server.Push.NoneMessage buildPartial() {
        com.nailong.xt.proto.server.Push.NoneMessage result = new com.nailong.xt.proto.server.Push.NoneMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nailong.xt.proto.server.Push.NoneMessage) {
          return mergeFrom((com.nailong.xt.proto.server.Push.NoneMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nailong.xt.proto.server.Push.NoneMessage other) {
        if (other == com.nailong.xt.proto.server.Push.NoneMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nailong.xt.proto.server.NoneMessage)
    }

    // @@protoc_insertion_point(class_scope:com.nailong.xt.proto.server.NoneMessage)
    private static final com.nailong.xt.proto.server.Push.NoneMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nailong.xt.proto.server.Push.NoneMessage();
    }

    public static com.nailong.xt.proto.server.Push.NoneMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoneMessage>
        PARSER = new com.google.protobuf.AbstractParser<NoneMessage>() {
      @java.lang.Override
      public NoneMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NoneMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoneMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nailong.xt.proto.server.Push.NoneMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nailong_xt_proto_server_PushPacketNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nailong_xt_proto_server_NoneMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021server/push.proto\022\033com.nailong.xt.prot" +
      "o.server\"\212\001\n\020PushPacketNotify\022\016\n\006cmd_id\030" +
      "\001 \001(\r\022\022\n\nproto_data\030\002 \001(\014\022\032\n\022target_play" +
      "er_uids\030\003 \003(\r\022\r\n\005token\030e \001(\t\022\023\n\013account_" +
      "uid\030f \001(\003\022\022\n\ttimestamp\030\311\001 \001(\004\"\r\n\013NoneMes" +
      "sage2\357\001\n\021ServerPushService\022m\n\020CreatePush" +
      "Stream\022(.com.nailong.xt.proto.server.Non" +
      "eMessage\032-.com.nailong.xt.proto.server.P" +
      "ushPacketNotify0\001\022k\n\020PushSingleNotify\022-." +
      "com.nailong.xt.proto.server.PushPacketNo" +
      "tify\032(.com.nailong.xt.proto.server.NoneM" +
      "essageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nailong_xt_proto_server_PushPacketNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nailong_xt_proto_server_PushPacketNotify_descriptor,
        new java.lang.String[] { "CmdId", "ProtoData", "TargetPlayerUids", "Token", "AccountUid", "Timestamp", });
    internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nailong_xt_proto_server_NoneMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nailong_xt_proto_server_NoneMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
